export default [
    {
        field: 'id',
        header: 'Id',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'category',
        subfield: 'categoryName',
        header: 'Category',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'subjectName',
        header: `Subject Name`,
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'CreatedBy',
        header: 'Created By',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'createdDate',
        header: 'Created Date',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'lastUpdatedBy',
        header: 'Last Updated By',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'lastUpdatedDate',
        header: 'Last Updated Date',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'isDeleted',
        header: 'Is Deleted',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
];
