export default [
    {
        field: 'id',
        header: 'Id',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'studentId',
        header: 'Student Id',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'packageName',
        header: 'Package Name',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'quantityCourse',
        header: 'Quantity Course',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'totalPrice',
        header: 'Total Price',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'startDate',
        header: 'Start Date',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'endDate',
        header: 'End Date',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    
    {
        field: 'isActive',
        header: 'Is Active',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'createdBy',
        header: 'Created By',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'createdDate',
        header: 'Created Date',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'lastUpdatedBy',
        header: 'Last Updated By',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'lastUpdatedDate',
        header: 'Last Updated Date',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'isDeleted',
        header: 'Is Deleted',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
];
