export default [
    {
        field: 'id',
        header: 'Id',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'package',
        subfield: 'packageName',
        header: 'Package Name',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'paymentMethod',
        header: `Payment Method`,
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'amount',
        header: 'Amount',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'totalPrice',
        header: 'Total Price',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'description',
        header: 'Description',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'status',
        header: 'Status',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'createdBy',
        header: 'Created By',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'createdDate',
        header: 'Created Date',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'lastUpdatedBy',
        header: 'Last Updated By',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'lastUpdatedDate',
        header: 'Last Updated Date',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'isDeleted',
        header: 'Is Deleted',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
];
