export default [
    {
        field: 'id',
        header: 'Id',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'course',
        subfield: 'code',
        header: 'Course Code',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'sessionName',
        header: `Session Name`,
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'title',
        header: 'Title',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'description',
        header: 'Description',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'learnDate',
        header: 'Learn Date',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'CreatedBy',
        header: 'Created By',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'createdDate',
        header: 'Created Date',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'lastUpdatedBy',
        header: 'Last Updated By',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'lastUpdatedDate',
        header: 'Last Updated Date',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'isDeleted',
        header: 'Is Deleted',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
];
