export default [
    {
        field: 'id',
        header: 'Id',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'subject',
        subfield: 'subjectName',
        header: 'Subject',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'provider',
        subfield: 'companyName',
        header: `Provider's Company`,
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'code',
        header: 'Code',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'courseName',
        header: 'Course Name',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'description',
        header: 'Description',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'price',
        header: 'Price',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'totalSessions',
        header: 'Total Sessions',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'soldCourses',
        header: 'Sold Courses',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    
    {
        field: 'totalSlots',
        header: 'Total Slots',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'isApproved',
        header: 'Is Approved',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'isActive',
        header: 'Is Active',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'startDate',
        header: 'Start Date',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },

    {
        field: 'createdBy',
        header: 'Created By',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'createdDate',
        header: 'Created Date',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'lastUpdatedBy',
        header: 'Last Updated By',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'lastUpdatedDate',
        header: 'Last Updated Date',
        isDisabled: true,
        sortIcon: true,
        sortField: true,
    },
    {
        field: 'isDeleted',
        header: 'Is Deleted',
        isDisabled: false,
        sortIcon: true,
        sortField: true,
    },
];
